import ProjectCard from "./project_card";

const AI_NUTRITIONIST_IMAGES = [
  {
    src: "/ai_landing.png",
    description: "Landing Page for AI Nutritionist App",
  },
  {
    src: "/ai_current.png",
    description:
      "Page that displays the current meal plan last generated by the user",
  },
  {
    src: "/ai_macros.png",
    description: "Page for changing macronutrients used for generating plans",
  },
  {
    src: "/ai_previous.png",
    description:
      "Previous meal page displaying all the previously generated meals",
  },
  {
    src: "/ai_previous_modal.png",
    description:
      "Modal popup for displaying meals accessed from previous meal page",
  },
];
const FITNESS_APP_IMAGES = [
  {
    src: "/fitness_landing.png",
    description: "Landing Page for Fitness Tracker",
  },
  {
    src: "/fitness_dashboard.PNG",
    description: "Logged in View for Fitness Tracker",
  },
  { src: "/fitness_session.png", description: "Tracked Workouts view" },
  {
    src: "/fitness_session_exercise.png",
    description: "Modal for adding an exercise to a session",
  },
  {
    src: "/fitness_exercise.png",
    description: "Modal for creating exercises",
  },
];

const TODO_APP_IMAGES = [
  { src: "/kanban_todo.png", description: "Kanban Board for Todo App" },
  { src: "/dashboard_todo.png", description: "Dashboard for Todo App" },
  { src: "/list_view_todo.png", description: "List View for Todo App" },
  { src: "/achievments_todo.png", description: "Achievements for Todo App" },
  { src: "/calendar_todo.png", description: "Calendar View for Todo App" },
];

const FOOD_APP_IMAGES = [
  { src: "/food_landing.png", description: "Dashboard for Food Recommender" },
  {
    src: "/food_nearby.PNG",
    description: "Nearby search for cuisines and restaurants",
  },
  {
    src: "/food_search_results.png",
    description: "Search functionality to search for particular restaurant",
  },
  {
    src: "/food_result.png",
    description: "Overview of restaurant with details on the restuarant",
  },
];

export function Projects() {
  return (
    <div
      className="mx-auto items-center justify-center mt-5 flex flex-col space-y-20"
      id="projects"
    >
      <div className="font-bold text-center space-y-2">
        <h2 className="text-lg text-gray-500 animate-fade-in-down">
          Browse My Recent
        </h2>
        <h2 className="text-6xl bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent py-1">
          Projects
        </h2>
      </div>

      {/* AI Nutritionist App */}
      <ProjectCard
        title={"AI Nutritionist"}
        images={AI_NUTRITIONIST_IMAGES}
        link={""}
        description={
          "AI nutritionist that uses Gemini 2.5 to generate meals based on inputted macronutrients"
        }
        skills={[
          "TypeScript",
          "Next.js",
          "React",
          "DynamoDB",
          "AWS EC2",
          "Gemini 2.5 Flash",
        ]}
      />

      {/* Fitness Tracker App */}
      <ProjectCard
        title={"Fitness Tracker"}
        images={FITNESS_APP_IMAGES}
        link={"https://fitness-app-bl5i.vercel.app/"}
        description={
          "Born from my passion for fitness, this app provides a streamlined experience for workout enthusiasts. It offers a clean, intuitive platform where users can effortlessly track their exercises, monitor progress, and implement progressive overload—the key to consistent strength gains and fitness improvement."
        }
        skills={["TypeScript", "Next.js", "React", "PostgreSQL", "TailwindCSS"]}
      />

      {/* Team Management App */}
      <ProjectCard
        title={"Team Management App"}
        images={TODO_APP_IMAGES}
        link={""}
        description={
          "A team management application that streamlines task organization, allowing members to establish priorities and track deadlines collaboratively."
        }
        skills={["TypeScript", "NextJS", "React", "PostgreSQL", "MaterialUI"]}
      />

      {/* Food Recommending App */}
      <ProjectCard
        title={"Food Recommender"}
        images={FOOD_APP_IMAGES}
        link={"https://my-app-azure-tau.vercel.app/"}
        description={
          "A Food Recommending application designed to help users discover local and popular cuisines utilising geolocation services."
        }
        skills={[
          "TypeScript",
          "React",
          "NodeJS",
          "ExpressJs",
          "Google Maps API",
        ]}
      />
    </div>
  );
}
